nfq_weather:
    provider: delegating
    providers:
        openweathermap:
            api_key: 'secretapikey'
        delegating:
            providers:
                - yahoo
                - openweathermap