nfq_weather:
    provider: delegating
    providers:
        openweathermap:
            api_key: 'c5fb386073ea22eb1f32d78dcdb0197d'
        delegating:
            providers:
                - yahoo
                - openweathermap