services:
    _defaults:
        public: false

    nfq_weather.provider.openweathermap:
        class: Nfq\WeatherBundle\OpenWeatherMapWeatherProvider
#        FIXME hardcoded apikey
        arguments: ['c5fb386073ea22eb1f32d78dcdb0197d']

    nfq_weather.provider.yahoo:
        class: Nfq\WeatherBundle\YahooWeatherProvider
        arguments: ['']

    nfq_weather.provider.delegating:
        class: Nfq\WeatherBundle\DelegatingWeatherProvider
        arguments: ['']

